/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    HospitalCards: typeof import('./src/components/HospitalCards.vue')['default']
    HospitalCardSkeleton: typeof import('./src/components/HospitalCardSkeleton.vue')['default']
    HospitalCardsLoading: typeof import('./src/components/HospitalCardsLoading.vue')['default']
    HospitalComments: typeof import('./src/components/HospitalComments.vue')['default']
    HospitalList: typeof import('./src/components/HospitalList.vue')['default']
    ICiHamburgerLg: typeof import('~icons/ci/hamburger-lg')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IIconParkOutlineBack: typeof import('~icons/icon-park-outline/back')['default']
    ILucidePhoneCall: typeof import('~icons/lucide/phone-call')['default']
    IMaterialSymbolsDashboard: typeof import('~icons/material-symbols/dashboard')['default']
    LocationSelect: typeof import('./src/components/LocationSelect.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoWhite: typeof import('./src/components/LogoWhite.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareModal: typeof import('./src/components/ShareModal.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabsWrapper: typeof import('./src/components/TabsWrapper.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
