/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HospitalCard: typeof import('./src/components/HospitalCard.vue')['default']
    HospitalList: typeof import('./src/components/HospitalList.vue')['default']
    ICiHamburgerLg: typeof import('~icons/ci/hamburger-lg')['default']
    ICiHamburgerMd: typeof import('~icons/ci/hamburger-md')['default']
    IClarityNotificationLine: typeof import('~icons/clarity/notification-line')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IIconParkOutlineBack: typeof import('~icons/icon-park-outline/back')['default']
    ILucidePhoneCall: typeof import('~icons/lucide/phone-call')['default']
    IMaterialSymbolsDashboard: typeof import('~icons/material-symbols/dashboard')['default']
    IMdiCaretDown: typeof import('~icons/mdi/caret-down')['default']
    IMdiCaretUp: typeof import('~icons/mdi/caret-up')['default']
    IMin: typeof import('~icons/mi/n')['default']
    IMingcuteDown: typeof import('~icons/mingcute/down')['default']
    IMingcuteDownFill: typeof import('~icons/mingcute/down-fill')['default']
    LocationSelect: typeof import('./src/components/LocationSelect.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareModal: typeof import('./src/components/ShareModal.vue')['default']
    ShareValues: typeof import('./src/components/ShareValues.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabsWrapper: typeof import('./src/components/TabsWrapper.vue')['default']
  }
}
