export type HospitalForm = {
    name: string,
    email: string,
    address: string,
    number: string,
    website: string,
    departments: string[],
    emergencyCare: boolean,
    emergencyCareDetails: string,
    accommodation: boolean,
    accommodationDetails: string,
    operatingFrom: string,
    operatingTo: string,
    insuranceProviders: string[],
    paymentMethods: string[],
    facilities: boolean,
    facilitiesDetails: string[],
    appointment: string,
    accessibilityFeatures: string[],
    languageServices: string,
    visitFrom: string,
    visitTo: string,
    visitGuide: string,
}