export type HospitalForm = {
    id?: string;
    accessibility: boolean,
    accessibilityFeatures: string[],
    accommodation: boolean,
    accommodationDetails: string,
    address: string,
    appointment: string,
    departments: string[],
    email: string,
    extraInfo: string,
    emergencyCare: boolean,
    emergencyCareDetails: string,
    facilities: boolean,
    facilitiesDetails: string[],
    insurance: boolean,
    insuranceProviders: string[],
    languageServices: string,
    name: string,
    operatingFrom: string,
    operatingTo: string,
    paymentMethods: string[],
    telephone: string,
    visitFrom: string,
    visitTo: string,
    visitGuide: string,
    website: string,
}